[project]
name = "order_service"
version = "0.1.0"
description = "Сервис для добавления товаров в заказ (тестовое задание)"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "psycopg2-binary",
    "pydantic",
]
